### ISSUE TITLE
Disconnect to opc.tcp://opcuaserver.com:4840 via Online OPC UA Client

### ISSUE THREAD

**Issue by RaymondCui21** [onewayautomation/OpcUaWebClient#1]
There are  two issues after logged on the OPC-UA online client (https://www.uaclient.com/) with my Google email account.

Steps to replicate: 

At the Addressspace, I added the "Local Discovery Server" opc.tcp://opcuaserver.com:4840 which is provided by the website http://opcuaserver.com

Two issues: 

1 At the block of log messages, it showed that the server is not connected;
2 When I successfully connect to the other server (OPC UA Demo Weather Server opc.tcp://opcuaserver.com:48484	), it can not add item at the monitored item view of view block. 

Thank you very much.

Kind regards,

Raymond

**Comment by RavilN** [comment]
Hi Raymond,

Thank you for reporting issues,

I need some clarifications. 

First, in the "Edit UA Server connection settings" dialog window, did you enter "opc.tcp://opcuaserver.com:4840" in fields "Endpoint URL" and "Discovery URL"? If yes, then from the "Address Space" panel it will not connect, and it is normal behavior, because this URL is for the Local Discovery Server, which does not support CreateSession and ActivateSession requests required to establish OPC UA Session.

Second, I tried to connect to the Demo Weather Server right now, and could add monitored items. Please note that  in order to add items, you need to select one more variables in the address space, and then click on the button with icon like |->|, with hint message "Add monitored item". After adding, values will not change frequently, they will only change every 15 minutes. Because weather data does not change with high frequency,  not every second, and to keep costs of getting weather data low, this limitation was added.
If you still cannot add monitored items, please let me know, with more detailed description of steps.

**Comment by RaymondCui21** [comment]
Hi RavilN,

Thank you very much.
The issues are solved followed by your guide. I can view the temperature of Earlwood at Australia now. 

When I right clicked one item in Views, it showed me three actions: "Add, Edit, Delete". The first two actions display "Action "Add" is not implemented yet". I am wondering whether there is any option to use these two actions?  
Also, is there any function to monitor all the historical temperature data, such as dashboard or API to download? Thank you very much.
Kind regards,

Raymond

**Comment by RavilN** [comment]
Hi Raymond,
At this stage actions in Views panel are not implemented yet.
And it does not render historical data yet. 
There is another tool, maybe it can server your needs: OPC UA Data Logger t https://github.com/onewayautomation/OPC-UA-Data-Logger
It can write data from OPC UA Servers to PostGreSQL database, and then that data can be rendered using Grafana. Grafana can display historical data as well as real time data.
BTW, the Demo Weather server does not provide historical data, only real time.

**Comment by RaymondCui21** [comment]
Thank you very much for the prompt reply and valuable suggestions!

**Comment by RavilN** [comment]
You are welcome, Raymond!
